import type { ArticleWithRelations, Category, Author } from '@/types';

export const mockCategories: Category[] = [
  {
    id: '1',
    name: 'Systems Innovations',
    slug: 'systems-innovations',
    description: 'Exploring cutting-edge approaches to system design and optimization',
    color: '#0EA5E9',
    icon: 'Zap',
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Integrated Risk Management',
    slug: 'integrated-risk-management',
    description: 'Comprehensive strategies for identifying and mitigating risks',
    color: '#F59E0B',
    icon: 'Shield',
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Resilience',
    slug: 'resilience',
    description: 'Building adaptive capacity in organizations and systems',
    color: '#10B981',
    icon: 'Heart',
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'AI and Analytics',
    slug: 'ai-and-analytics',
    description: 'Leveraging artificial intelligence and data analytics for insights',
    color: '#8B5CF6',
    icon: 'Brain',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Real-Time Leadership',
    slug: 'real-time-leadership',
    description: 'Modern leadership strategies for dynamic environments',
    color: '#EC4899',
    icon: 'Users',
    created_at: new Date().toISOString(),
  },
];

export const mockAuthor: Author = {
  id: '1',
  user_id: null,
  name: 'Alvin Silva',
  email: 'alvin.silva@asilvainnovations.com',
  bio: 'Founder and CEO of ASilva Innovations. Alvin is a recognized thought leader in systems innovation, risk management, and organizational resilience. With over 20 years of experience helping organizations navigate complex challenges, he brings a unique perspective on building adaptive, high-performing enterprises.',
  avatar_url: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop&crop=face',
  role: 'admin',
  social_links: {
    twitter: 'https://twitter.com/alvinsilva',
    linkedin: 'https://linkedin.com/in/alvinsilva',
    website: 'https://asilvainnovations.com',
  },
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const mockArticles: ArticleWithRelations[] = [
  {
    id: '1',
    title: 'The Future of Systems Innovation in Enterprise Architecture',
    slug: 'future-systems-innovation-enterprise-architecture',
    excerpt: 'Exploring how modern enterprises are leveraging systems thinking to build more resilient, adaptive, and innovative organizational structures.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: "In today's rapidly evolving business landscape, organizations must embrace systems innovation to remain competitive. This comprehensive approach to enterprise architecture goes beyond traditional siloed thinking, fostering interconnected solutions that drive sustainable growth.",
        order: 1,
      },
      {
        id: '2',
        type: 'heading',
        content: 'Understanding Systems Innovation',
        metadata: { level: 2 },
        order: 2,
      },
      {
        id: '3',
        type: 'paragraph',
        content: 'Systems innovation represents a paradigm shift in how we approach organizational challenges. Rather than addressing symptoms in isolation, it focuses on understanding and optimizing the entire ecosystem of people, processes, and technologies.',
        order: 3,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '1',
    status: 'published',
    published_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 8,
    view_count: 1250,
    meta_title: 'Systems Innovation in Enterprise Architecture | ASilva Innovations',
    meta_description: 'Discover how systems thinking transforms enterprise architecture for sustainable competitive advantage.',
    canonical_url: null,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[0],
    tags: [],
  },
  {
    id: '2',
    title: 'Integrated Risk Management: A Holistic Approach',
    slug: 'integrated-risk-management-holistic-approach',
    excerpt: 'Why traditional risk management approaches fall short and how integrated frameworks provide comprehensive protection for modern organizations.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: 'Traditional risk management often operates in silos, with different departments managing their own risks independently. This fragmented approach leaves organizations vulnerable to interconnected threats that span multiple domains.',
        order: 1,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '2',
    status: 'published',
    published_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 6,
    view_count: 980,
    meta_title: null,
    meta_description: null,
    canonical_url: null,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[1],
    tags: [],
  },
  {
    id: '3',
    title: 'Building Organizational Resilience in Uncertain Times',
    slug: 'building-organizational-resilience',
    excerpt: 'Key strategies for developing adaptive capacity that helps organizations thrive amid disruption and uncertainty.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: "Resilience is no longer just a buzzword—it's a critical organizational capability. In an era of constant change and disruption, the ability to adapt, recover, and even thrive in the face of challenges separates market leaders from laggards.",
        order: 1,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '3',
    status: 'published',
    published_at: new Date(Date.now() - 21 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 7,
    view_count: 850,
    meta_title: null,
    meta_description: null,
    canonical_url: null,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[2],
    tags: [],
  },
  {
    id: '4',
    title: 'AI and Analytics: Transforming Decision-Making',
    slug: 'ai-analytics-transforming-decision-making',
    excerpt: 'How artificial intelligence and advanced analytics are revolutionizing the way organizations make strategic decisions.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: 'The convergence of artificial intelligence and advanced analytics is creating unprecedented opportunities for data-driven decision-making. Organizations that successfully harness these technologies gain significant competitive advantages.',
        order: 1,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '4',
    status: 'published',
    published_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 9,
    view_count: 1100,
    meta_title: null,
    meta_description: null,
    canonical_url: null,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[3],
    tags: [],
  },
  {
    id: '5',
    title: 'Real-Time Leadership: Navigating Dynamic Environments',
    slug: 'real-time-leadership-dynamic-environments',
    excerpt: 'The essential skills and mindsets leaders need to guide their organizations through rapidly changing business landscapes.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: 'Leadership in the modern era requires a fundamentally different approach. The pace of change demands leaders who can make decisions quickly, adapt to new information, and guide their teams through uncertainty with confidence.',
        order: 1,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '5',
    status: 'published',
    published_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 6,
    view_count: 920,
    meta_title: null,
    meta_description: null,
    canonical_url: null,
    featured: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[4],
    tags: [],
  },
  {
    id: '6',
    title: 'Designing Adaptive Systems for Complex Challenges',
    slug: 'designing-adaptive-systems',
    excerpt: 'A deep dive into the principles and practices of creating systems that can evolve and adapt to changing requirements.',
    content: [
      {
        id: '1',
        type: 'paragraph',
        content: 'Adaptive systems are designed to evolve in response to changing conditions. Unlike rigid systems that require complete overhauls when requirements shift, adaptive systems can modify their behavior and structure while maintaining core functionality.',
        order: 1,
      },
    ],
    featured_image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&h=630&fit=crop',
    author_id: '1',
    category_id: '1',
    status: 'published',
    published_at: new Date(Date.now() - 28 * 24 * 60 * 60 * 1000).toISOString(),
    scheduled_at: null,
    read_time: 10,
    view_count: 750,
    meta_title: null,
    meta_description: null,
    canonical_url: null,
    featured: false,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    author: mockAuthor,
    category: mockCategories[0],
    tags: [],
  },
];
